<?xml version="1.0" encoding="utf-8"?><Database Name="dbToDoTasks" Class="dbToDoTasksDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=dbToDoTasks;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dbToDoTasksConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="email" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="Account_Sync" Member="Syncs" ThisKey="email" OtherKey="email" Type="Sync" />
    </Type>
  </Table>
  <Table Name="dbo.Sync" Member="Syncs">
    <Type Name="Sync">
      <Column Name="email" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="datesync" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="filesync" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Account_Sync" Member="Account" ThisKey="email" OtherKey="email" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
</Database>